import { Topic } from './types';

export const topics: Topic[] = [
      {
            id: "Food",
            title: "Food",
            description: "Vocabulary related to food and drinks in different languages.",
            cards: [
                  { english: "apple", german: "Apfel", spanish: "manzana" },
                  { english: "bread", german: "Brot", spanish: "pan" },
                  { english: "cheese", german: "Käse", spanish: "queso" },
                  { english: "milk", german: "Milch", spanish: "leche" },
                  { english: "water", german: "Wasser", spanish: "agua" },
                  { english: "coffee", german: "Kaffee", spanish: "café" },
                  { english: "tea", german: "Tee", spanish: "té" },
                  { english: "juice", german: "Saft", spanish: "zumo/jugo" },
                  { english: "beer", german: "Bier", spanish: "cerveza" },
                  { english: "wine", german: "Wein", spanish: "vino" },
                  { english: "rice", german: "Reis", spanish: "arroz" },
                  { english: "pasta", german: "Nudeln", spanish: "pasta" },
                  { english: "potato", german: "Kartoffel", spanish: "patata" },
                  { english: "tomato", german: "Tomate", spanish: "tomate" },
                  { english: "onion", german: "Zwiebel", spanish: "cebolla" },
                  { english: "garlic", german: "Knoblauch", spanish: "ajo" },
                  { english: "carrot", german: "Karotte", spanish: "zanahoria" },
                  { english: "lettuce", german: "Salat", spanish: "lechuga" },
                  { english: "chicken", german: "Hähnchen", spanish: "pollo" },
                  { english: "beef", german: "Rindfleisch", spanish: "carne de res" },
                  { english: "pork", german: "Schweinefleisch", spanish: "cerdo" },
                  { english: "fish", german: "Fisch", spanish: "pescado" },
                  { english: "egg", german: "Ei", spanish: "huevo" },
                  { english: "butter", german: "Butter", spanish: "mantequilla" },
                  { english: "yogurt", german: "Joghurt", spanish: "yogur" },
                  { english: "sugar", german: "Zucker", spanish: "azúcar" },
                  { english: "salt", german: "Salz", spanish: "sal" },
                  { english: "pepper", german: "Pfeffer", spanish: "pimienta" },
                  { english: "oil", german: "Öl", spanish: "aceite" },
                  { english: "vinegar", german: "Essig", spanish: "vinagre" },
                  { english: "honey", german: "Honig", spanish: "miel" },
                  { english: "flour", german: "Mehl", spanish: "harina" },
                  { english: "soup", german: "Suppe", spanish: "sopa" },
                  { english: "salad", german: "Salat", spanish: "ensalada" },
                  { english: "sandwich", german: "Sandwich", spanish: "sándwich" },
                  { english: "pizza", german: "Pizza", spanish: "pizza" },
                  { english: "hamburger", german: "Hamburger", spanish: "hamburguesa" },
                  { english: "ice cream", german: "Eis", spanish: "helado" },
                  { english: "chocolate", german: "Schokolade", spanish: "chocolate" },
                  { english: "cake", german: "Kuchen", spanish: "pastel/tarta" },
                  { english: "cookie", german: "Keks", spanish: "galleta" },
                  { english: "banana", german: "Banane", spanish: "plátano" },
                  { english: "orange", german: "Orange", spanish: "naranja" },
                  { english: "strawberry", german: "Erdbeere", spanish: "fresa" },
                  { english: "grape", german: "Traube", spanish: "uva" },
                  { english: "lemon", german: "Zitrone", spanish: "limón" },
                  { english: "pear", german: "Birne", spanish: "pera" },
                  { english: "pineapple", german: "Ananas", spanish: "piña" },
                  { english: "watermelon", german: "Wassermelone", spanish: "sandía" },
                  { english: "peach", german: "Pfirsich", spanish: "melocotón" },
                  { english: "cherry", german: "Kirsche", spanish: "cereza" },
                  { english: "cucumber", german: "Gurke", spanish: "pepino" },
                  { english: "pepper", german: "Paprika", spanish: "pimiento" },
                  { english: "mushroom", german: "Pilz", spanish: "champiñón" },
                  { english: "avocado", german: "Avocado", spanish: "aguacate" },
                  { english: "olive oil", german: "Olivenöl", spanish: "aceite de oliva" },
                  { english: "quinoa", german: "Quinoa", spanish: "quinua" },
                  { english: "sushi", german: "Sushi", spanish: "sushi" },
                  { english: "hummus", german: "Hummus", spanish: "hummus" },
                  { english: "cinnamon", german: "Zimt", spanish: "canela" },
                  { english: "ginger", german: "Ingwer", spanish: "jengibre" },
                  { english: "sparkling water", german: "Sprudelwasser", spanish: "agua con gas" },
                  { english: "herbal tea", german: "Kräutertee", spanish: "té de hierbas" },
                  { english: "red wine", german: "Rotwein", spanish: "vino tinto" },
                  { english: "white wine", german: "Weißwein", spanish: "vino blanco" },
                  { english: "craft beer", german: "Craft-Bier", spanish: "cerveza artesanal" },
                  { english: "dark chocolate", german: "dunkle Schokolade", spanish: "chocolate negro" },
                  { english: "sea salt", german: "Meersalz", spanish: "sal marina" },
                  { english: "black pepper", german: "schwarzer Pfeffer", spanish: "pimienta negra" },
                  { english: "vanilla extract", german: "Vanilleextrakt", spanish: "extracto de vainilla" },
                  { english: "sourdough bread", german: "Sauerteigbrot", spanish: "pan de masa madre" },
                  { english: "cottage cheese", german: "Hüttenkäse", spanish: "requesón" },
                  { english: "almond milk", german: "Mandelmilch", spanish: "leche de almendras" },
                  { english: "protein shake", german: "Proteinshake", spanish: "batido de proteínas" },
                  { english: "lentils", german: "Linsen", spanish: "lentejas" },
                  { english: "chickpeas", german: "Kichererbsen", spanish: "garbanzos" },
                  { english: "tofu", german: "Tofu", spanish: "tofu" },
                  { english: "salmon", german: "Lachs", spanish: "salmón" },
                  { english: "tuna", german: "Thunfisch", spanish: "atún" },
                  { english: "shrimp", german: "Garnelen", spanish: "gambas" },
                  { english: "mussels", german: "Miesmuscheln", spanish: "mejillones" },
                  { english: "octopus", german: "Tintenfisch", spanish: "pulpo" },
                  { english: "sausage", german: "Wurst", spanish: "salchicha" },
                  { english: "bacon", german: "Speck", spanish: "tocino" },
                  { english: "ham", german: "Schinken", spanish: "jamón" },
                  { english: "mustard", german: "Senf", spanish: "mostaza" },
                  { english: "ketchup", german: "Ketchup", spanish: "ketchup" },
                  { english: "mayonnaise", german: "Mayonnaise", spanish: "mayonesa" },
                  { english: "soy sauce", german: "Sojasauce", spanish: "salsa de soja" },
                  { english: "salsa", german: "Salsa", spanish: "salsa" },
                  { english: "guacamole", german: "Guacamole", spanish: "guacamole" },
                  { english: "pancakes", german: "Pfannkuchen", spanish: "tortitas" },
                  { english: "waffles", german: "Waffeln", spanish: "gofres" },
                  { english: "croissant", german: "Croissant", spanish: "croissant" },
                  { english: "baguette", german: "Baguette", spanish: "baguette" },
                  { english: "cereal", german: "Müsli", spanish: "cereales" },
                  { english: "oatmeal", german: "Haferbrei", spanish: "avena" },
                  { english: "granola", german: "Granola", spanish: "granola" },
                  { english: "smoothie", german: "Smoothie", spanish: "batido" },
                  { english: "milkshake", german: "Milchshake", spanish: "batido de leche" },
                  { english: "espresso", german: "Espresso", spanish: "espresso" },
                  { english: "cappuccino", german: "Cappuccino", spanish: "capuchino" },
                  { english: "latte", german: "Latte", spanish: "latte" },
                  { english: "whiskey", german: "Whiskey", spanish: "whisky" },
                  { english: "vodka", german: "Wodka", spanish: "vodka" },
                  { english: "rum", german: "Rum", spanish: "ron" },
                  { english: "gin", german: "Gin", spanish: "ginebra" },
                  { english: "cocktail", german: "Cocktail", spanish: "cóctel" },
                  { english: "lemonade", german: "Limonade", spanish: "limonada" },
                  { english: "iced tea", german: "Eistee", spanish: "té helado" },
                  { english: "sparkling wine", german: "Sekt", spanish: "vino espumoso" },
                  { english: "champagne", german: "Champagner", spanish: "champán" }
            ],
      },
      {
            id: "House",
            title: "House",
            description: "Vocabulary of things and parts of the house, from basic to B2 level.",
            cards: [
                  { english: "chair", german: "Stuhl", spanish: "silla" },
                  { english: "table", german: "Tisch", spanish: "mesa" },
                  { english: "window", german: "Fenster", spanish: "ventana" },
                  { english: "door", german: "Tür", spanish: "puerta" },
                  { english: "bed", german: "Bett", spanish: "cama" },
                  { english: "sofa", german: "Sofa", spanish: "sofá" },
                  { english: "lamp", german: "Lampe", spanish: "lámpara" },
                  { english: "rug", german: "Teppich", spanish: "alfombra" },
                  { english: "curtain", german: "Vorhang", spanish: "cortina" },
                  { english: "wall", german: "Wand", spanish: "pared" },
                  { english: "floor", german: "Boden", spanish: "suelo" },
                  { english: "ceiling", german: "Decke", spanish: "techo" },
                  { english: "roof", german: "Dach", spanish: "tejado" },
                  { english: "kitchen", german: "Küche", spanish: "cocina" },
                  { english: "bathroom", german: "Badezimmer", spanish: "baño" },
                  { english: "bedroom", german: "Schlafzimmer", spanish: "dormitorio" },
                  { english: "living room", german: "Wohnzimmer", spanish: "salón" },
                  { english: "hallway", german: "Flur", spanish: "pasillo" },
                  { english: "garage", german: "Garage", spanish: "garaje" },
                  { english: "garden", german: "Garten", spanish: "jardín" },
                  { english: "balcony", german: "Balkon", spanish: "balcón" },
                  { english: "staircase", german: "Treppe", spanish: "escalera" },
                  { english: "attic", german: "Dachboden", spanish: "ático" },
                  { english: "basement", german: "Keller", spanish: "sótano" },
                  { english: "shower", german: "Dusche", spanish: "ducha" },
                  { english: "bathtub", german: "Badewanne", spanish: "bañera" },
                  { english: "toilet", german: "Toilette", spanish: "inodoro" },
                  { english: "sink", german: "Waschbecken", spanish: "lavabo" },
                  { english: "mirror", german: "Spiegel", spanish: "espejo" },
                  { english: "refrigerator", german: "Kühlschrank", spanish: "nevera/refrigerador" },
                  { english: "oven", german: "Ofen", spanish: "horno" },
                  { english: "microwave", german: "Mikrowelle", spanish: "microondas" },
                  { english: "dishwasher", german: "Geschirrspüler", spanish: "lavavajillas" },
                  { english: "washing machine", german: "Waschmaschine", spanish: "lavadora" },
                  { english: "dryer", german: "Trockner", spanish: "secadora" },
                  { english: "closet", german: "Schrank", spanish: "armario" },
                  { english: "shelf", german: "Regal", spanish: "estantería" },
                  { english: "drawer", german: "Schublade", spanish: "cajón" },
                  { english: "key", german: "Schlüssel", spanish: "llave" },
                  { english: "lock", german: "Schloss", spanish: "cerradura" },
                  { english: "light switch", german: "Lichtschalter", spanish: "interruptor de luz" },
                  { english: "socket", german: "Steckdose", spanish: "enchufe" },
                  { english: "fireplace", german: "Kamin", spanish: "chimenea" },
                  { english: "furniture", german: "Möbel", spanish: "muebles" },
                  { english: "bookshelf", german: "Bücherregal", spanish: "librería" },
                  { english: "desk", german: "Schreibtisch", spanish: "escritorio" },
                  { english: "wardrobe", german: "Kleiderschrank", spanish: "armario ropero" },
                  { english: "hammock", german: "Hängematte", spanish: "hamaca" },
                  { english: "toolbox", german: "Werkzeugkasten", spanish: "caja de herramientas" },
                  { english: "vacuum cleaner", german: "Staubsauger", spanish: "aspiradora" },
                  { english: "iron", german: "Bügeleisen", spanish: "plancha" },
                  { english: "blinds", german: "Jalousien", spanish: "persianas" },
                  { english: "doormat", german: "Fußmatte", spanish: "felpudo" },
                  { english: "mailbox", german: "Briefkasten", spanish: "buzón" },
                  { english: "heater", german: "Heizung", spanish: "calefactor" },
                  { english: "air conditioner", german: "Klimaanlage", spanish: "aire acondicionado" },
                  { english: "alarm clock", german: "Wecker", spanish: "despertador" },
                  { english: "picture frame", german: "Bilderrahmen", spanish: "marco de fotos" },
                  { english: "plant", german: "Pflanze", spanish: "planta" },
                  { english: "vase", german: "Vase", spanish: "jarrón" },
                  { english: "umbrella stand", german: "Schirmständer", spanish: "paragüero" },
                  { english: "trash can", german: "Mülleimer", spanish: "papelera" },
                  { english: "hook", german: "Haken", spanish: "gancho" },
                  { english: "chimney", german: "Schornstein", spanish: "chimenea" },
                  { english: "porch", german: "Veranda", spanish: "porche" },
                  { english: "patio", german: "Innenhof", spanish: "patio" },
                  { english: "driveway", german: "Auffahrt", spanish: "entrada para autos" },
                  { english: "fence", german: "Zaun", spanish: "valla" },
                  { english: "gate", german: "Tor", spanish: "puerta principal/verja" },
                  { english: "shed", german: "Schuppen", spanish: "cobertizo" }
            ]
      },
      {
            id: "Animals",
            title: "Animals",
            description: "Words related to animals, from basic to B2 level.",
            cards: [
                  { english: "dog", german: "Hund", spanish: "perro" },
                  { english: "cat", german: "Katze", spanish: "gato" },
                  { english: "elephant", german: "Elefant", spanish: "elefante" },
                  { english: "lion", german: "Löwe", spanish: "león" },
                  { english: "tiger", german: "Tiger", spanish: "tigre" },
                  { english: "bear", german: "Bär", spanish: "oso" },
                  { english: "monkey", german: "Affe", spanish: "mono" },
                  { english: "giraffe", german: "Giraffe", spanish: "jirafa" },
                  { english: "zebra", german: "Zebra", spanish: "cebra" },
                  { english: "wolf", german: "Wolf", spanish: "lobo" },
                  { english: "fox", german: "Fuchs", spanish: "zorro" },
                  { english: "rabbit", german: "Hase", spanish: "conejo" },
                  { english: "mouse", german: "Maus", spanish: "ratón" },
                  { english: "rat", german: "Ratte", spanish: "rata" },
                  { english: "squirrel", german: "Eichhörnchen", spanish: "ardilla" },
                  { english: "deer", german: "Hirsch", spanish: "ciervo" },
                  { english: "horse", german: "Pferd", spanish: "caballo" },
                  { english: "donkey", german: "Esel", spanish: "burro" },
                  { english: "cow", german: "Kuh", spanish: "vaca" },
                  { english: "pig", german: "Schwein", spanish: "cerdo" },
                  { english: "sheep", german: "Schaf", spanish: "oveja" },
                  { english: "goat", german: "Ziege", spanish: "cabra" },
                  { english: "chicken", german: "Huhn", spanish: "pollo" },
                  { english: "duck", german: "Ente", spanish: "pato" },
                  { english: "turkey", german: "Truthahn", spanish: "pavo" },
                  { english: "penguin", german: "Pinguin", spanish: "pingüino" },
                  { english: "whale", german: "Wal", spanish: "ballena" },
                  { english: "dolphin", german: "Delfin", spanish: "delfín" },
                  { english: "shark", german: "Hai", spanish: "tiburón" },
                  { english: "octopus", german: "Krake", spanish: "pulpo" },
                  { english: "crab", german: "Krabbe", spanish: "cangrejo" },
                  { english: "lobster", german: "Hummer", spanish: "langosta" },
                  { english: "frog", german: "Frosch", spanish: "rana" },
                  { english: "snake", german: "Schlange", spanish: "serpiente" },
                  { english: "lizard", german: "Eidechse", spanish: "lagarto" },
                  { english: "turtle", german: "Schildkröte", spanish: "tortuga" },
                  { english: "crocodile", german: "Krokodil", spanish: "cocodrilo" },
                  { english: "alligator", german: "Alligator", spanish: "caimán" },
                  { english: "bat", german: "Fledermaus", spanish: "murciélago" },
                  { english: "owl", german: "Eule", spanish: "búho" },
                  { english: "eagle", german: "Adler", spanish: "águila" },
                  { english: "hawk", german: "Falke", spanish: "halcón" },
                  { english: "parrot", german: "Papagei", spanish: "loro" },
                  { english: "sparrow", german: "Spatz", spanish: "gorrión" },
                  { english: "swan", german: "Schwan", spanish: "cisne" },
                  { english: "duckling", german: "Entchen", spanish: "patito" },
                  { english: "kitten", german: "Kätzchen", spanish: "gatito" },
                  { english: "puppy", german: "Welpe", spanish: "cachorro" },
                  { english: "calf", german: "Kalb", spanish: "ternero" },
                  { english: "foal", german: "Fohlen", spanish: "potro" },
                  { english: "lamb", german: "Lamm", spanish: "cordero" },
                  { english: "bull", german: "Stier", spanish: "toro" },
                  { english: "buffalo", german: "Büffel", spanish: "búfalo" },
                  { english: "camel", german: "Kamel", spanish: "camello" },
                  { english: "hippopotamus", german: "Nilpferd", spanish: "hipopótamo" },
                  { english: "rhinoceros", german: "Nashorn", spanish: "rinoceronte" },
                  { english: "gorilla", german: "Gorilla", spanish: "gorila" },
                  { english: "chimp", german: "Schimpanse", spanish: "chimpancé" },
                  { english: "lemur", german: "Lemur", spanish: "lémur" },
                  { english: "panda", german: "Panda", spanish: "panda" },
                  { english: "koala", german: "Koala", spanish: "koala" },
                  { english: "kangaroo", german: "Känguru", spanish: "canguro" },
                  { english: "platypus", german: "Schnabeltier", spanish: "ornitorrinco" },
                  { english: "hedgehog", german: "Igel", spanish: "erizo" },
                  { english: "seal", german: "Robbe", spanish: "foca" },
                  { english: "walrus", german: "Morse", spanish: "morsa" },
                  { english: "antelope", german: "Antilope", spanish: "antílope" },
                  { english: "hyena", german: "Hyäne", spanish: "hiena" },
                  { english: "meerkat", german: "Erdmännchen", spanish: "suricata" },
                  { english: "beetle", german: "Käfer", spanish: "escarabajo" },
                  { english: "butterfly", german: "Schmetterling", spanish: "mariposa" },
                  { english: "dragonfly", german: "Libelle", spanish: "libélula" },
                  { english: "mosquito", german: "Mücke", spanish: "mosquito" },
                  { english: "spider", german: "Spinne", spanish: "araña" },
                  { english: "scorpion", german: "Skorpion", spanish: "escorpión" },
                  { english: "worm", german: "Wurm", spanish: "gusano" },
                  { english: "snail", german: "Schnecke", spanish: "caracol" }
            ]
      },
      {
            id: "Verbs",
            title: "Verbs (past, participle and infinitive)",
            description: "List of verbs in their different forms.",
            cards: [
                  { english: "eat", german: "essen", spanish: "comer" },
                  { english: "ate", german: "aß", spanish: "comió" },
                  { english: "eaten", german: "gegessen", spanish: "comido" },
            ],
      },
      {
            id: "CommonWords",
            title: "1500 most common words",
            description: "The most used words in everyday conversations. Level B2",
            cards: [
                  { "english": "the (masc.)", "german": "der", "spanish": "el" },
                  { "english": "the (fem.)", "german": "die", "spanish": "la" },
                  { "english": "the (neut.)", "german": "das", "spanish": "el/la" },
                  { "english": "a (masc.)", "german": "ein", "spanish": "un" },
                  { "english": "a (fem.)", "german": "eine", "spanish": "una" },
                  { "english": "he", "german": "er", "spanish": "él" },
                  { "english": "she", "german": "sie", "spanish": "ella" },
                  { "english": "it", "german": "es", "spanish": "eso/ello" },
                  { "english": "we", "german": "wir", "spanish": "nosotros" },
                  { "english": "you (plural)", "german": "ihr", "spanish": "vosotros/ustedes" },
                  { "english": "they", "german": "sie", "spanish": "ellos/ellas" },
                  { "english": "me", "german": "mich", "spanish": "me" },
                  { "english": "you", "german": "dich", "spanish": "te" },
                  { "english": "him", "german": "ihn", "spanish": "lo" },
                  { "english": "us", "german": "uns", "spanish": "nos" },
                  { "english": "you (plural)", "german": "euch", "spanish": "os" },
                  { "english": "to me", "german": "mir", "spanish": "me" },
                  { "english": "to you", "german": "dir", "spanish": "te" },
                  { "english": "to him", "german": "ihm", "spanish": "le" },
                  { "english": "to them", "german": "ihnen", "spanish": "les" },
                  { "english": "to be", "german": "sein", "spanish": "ser/estar" },
                  { "english": "to have", "german": "haben", "spanish": "tener" },
                  { "english": "to become", "german": "werden", "spanish": "llegar a ser" },
                  { "english": "can", "german": "können", "spanish": "poder" },
                  { "english": "must", "german": "müssen", "spanish": "deber" },
                  { "english": "to want", "german": "wollen", "spanish": "querer" },
                  { "english": "to should", "german": "sollen", "spanish": "debería" },
                  { "english": "to be allowed", "german": "dürfen", "spanish": "tener permiso" },
                  { "english": "to do/make", "german": "machen", "spanish": "hacer" },
                  { "english": "to say", "german": "sagen", "spanish": "decir" },
                  { "english": "to go", "german": "gehen", "spanish": "ir" },
                  { "english": "to come", "german": "kommen", "spanish": "venir" },
                  { "english": "to know", "german": "wissen", "spanish": "saber" },
                  { "english": "to see", "german": "sehen", "spanish": "ver" },
                  { "english": "to leave", "german": "lassen", "spanish": "dejar" },
                  { "english": "to stand", "german": "stehen", "spanish": "estar de pie" },
                  { "english": "to find", "german": "finden", "spanish": "encontrar" },
                  { "english": "to stay", "german": "bleiben", "spanish": "quedarse" },
                  { "english": "to lie (down)", "german": "liegen", "spanish": "estar acostado" },
                  { "english": "to take", "german": "nehmen", "spanish": "tomar" },
                  { "english": "to think", "german": "denken", "spanish": "pensar" },
                  { "english": "to do", "german": "tun", "spanish": "hacer" },
                  { "english": "to believe", "german": "glauben", "spanish": "creer" },
                  { "english": "to hold", "german": "halten", "spanish": "sostener" },
                  { "english": "to show", "german": "zeigen", "spanish": "mostrar" },
                  { "english": "and", "german": "und", "spanish": "y" },
                  { "english": "or", "german": "oder", "spanish": "o" },
                  { "english": "but", "german": "aber", "spanish": "pero" },
                  { "english": "because", "german": "weil", "spanish": "porque" },
                  { "english": "although", "german": "obwohl", "spanish": "aunque" },
                  { "english": "where", "german": "wo", "spanish": "dónde" },
                  { "english": "why", "german": "warum", "spanish": "por qué" },
                  { "english": "table", "german": "Tisch", "spanish": "mesa" },
                  { "english": "chair", "german": "Stuhl", "spanish": "silla" },
                  { "english": "car", "german": "Auto", "spanish": "coche" },
                  { "english": "house", "german": "Haus", "spanish": "casa" },
                  { "english": "school", "german": "Schule", "spanish": "escuela" },
                  { "english": "teacher", "german": "Lehrer", "spanish": "profesor" },
                  { "english": "student", "german": "Schüler", "spanish": "alumno" },
                  { "english": "friend", "german": "Freund", "spanish": "amigo" },
                  { "english": "dog", "german": "Hund", "spanish": "perro" },
                  { "english": "cat", "german": "Katze", "spanish": "gato" },
                  { "english": "milk", "german": "Milch", "spanish": "leche" },
                  { "english": "water", "german": "Wasser", "spanish": "agua" },
                  { "english": "beer", "german": "Bier", "spanish": "cerveza" },
                  { "english": "wine", "german": "Wein", "spanish": "vino" },
                  { "english": "apple", "german": "Apfel", "spanish": "manzana" },
                  { "english": "banana", "german": "Banane", "spanish": "plátano" },
                  { "english": "potato", "german": "Kartoffel", "spanish": "patata" },
                  { "english": "computer", "german": "Computer", "spanish": "ordenador" },
                  { "english": "window", "german": "Fenster", "spanish": "ventana" },
                  { "english": "door", "german": "Tür", "spanish": "puerta" },
                  { "english": "bed", "german": "Bett", "spanish": "cama" },
                  { "english": "lamp", "german": "Lampe", "spanish": "lámpara" },
                  { "english": "book", "german": "Buch", "spanish": "libro" },
                  { "english": "newspaper", "german": "Zeitung", "spanish": "periódico" },
                  { "english": "pen", "german": "Stift", "spanish": "bolígrafo" },
                  { "english": "paper", "german": "Papier", "spanish": "papel" },
                  { "english": "city", "german": "Stadt", "spanish": "ciudad" },
                  { "english": "village", "german": "Dorf", "spanish": "pueblo" },
                  { "english": "street", "german": "Straße", "spanish": "calle" },
                  { "english": "park", "german": "Park", "spanish": "parque" },
                  { "english": "train", "german": "Zug", "spanish": "tren" },
                  { "english": "bus", "german": "Bus", "spanish": "autobús" },
                  { "english": "airport", "german": "Flughafen", "spanish": "aeropuerto" },
                  { "english": "hotel", "german": "Hotel", "spanish": "hotel" },
                  { "english": "hospital", "german": "Krankenhaus", "spanish": "hospital" },
                  { "english": "doctor", "german": "Arzt", "spanish": "médico" },
                  { "english": "nurse", "german": "Krankenschwester", "spanish": "enfermera" },
                  { "english": "firefighter", "german": "Feuerwehrmann", "spanish": "bombero" },
                  { "english": "police officer", "german": "Polizist", "spanish": "policía" },
                  { "english": "worker", "german": "Arbeiter", "spanish": "trabajador" },
                  { "english": "boss", "german": "Chef", "spanish": "jefe" },
                  { "english": "store", "german": "Laden", "spanish": "tienda" },
                  { "english": "restaurant", "german": "Restaurant", "spanish": "restaurante" },
                  { "english": "market", "german": "Markt", "spanish": "mercado" },
                  { "english": "money", "german": "Geld", "spanish": "dinero" },
                  { "english": "price", "german": "Preis", "spanish": "precio" },
                  { "english": "food", "german": "Essen", "spanish": "comida" },
                  { "english": "bread", "german": "Brot", "spanish": "pan" },
                  { "english": "cheese", "german": "Käse", "spanish": "queso" },
                  { "english": "butter", "german": "Butter", "spanish": "mantequilla" },
                  { "english": "egg", "german": "Ei", "spanish": "huevo" },
                  { "english": "meat", "german": "Fleisch", "spanish": "carne" },
                  { "english": "chicken", "german": "Huhn", "spanish": "pollo" },
                  { "english": "fish", "german": "Fisch", "spanish": "pescado" },
                  { "english": "sugar", "german": "Zucker", "spanish": "azúcar" },
                  { "english": "salt", "german": "Salz", "spanish": "sal" },
                  { "english": "onion", "german": "Zwiebel", "spanish": "cebolla" },
                  { "english": "garlic", "german": "Knoblauch", "spanish": "ajo" },
                  { "english": "lettuce", "german": "Salat", "spanish": "lechuga" },
                  { "english": "pepper", "german": "Paprika", "spanish": "pimiento" },
                  { "english": "carrot", "german": "Karotte", "spanish": "zanahoria" },
                  { "english": "strawberry", "german": "Erdbeere", "spanish": "fresa" },
                  { "english": "grape", "german": "Traube", "spanish": "uva" },
                  { "english": "lemon", "german": "Zitrone", "spanish": "limón" },
                  { "english": "orange", "german": "Orange", "spanish": "naranja" },
                  { "english": "fruit", "german": "Obst", "spanish": "fruta" },
                  { "english": "vegetable", "german": "Gemüse", "spanish": "verdura" },
                  { "english": "cup", "german": "Tasse", "spanish": "taza" },
                  { "english": "plate", "german": "Teller", "spanish": "plato" },
                  { "english": "knife", "german": "Messer", "spanish": "cuchillo" },
                  { "english": "fork", "german": "Gabel", "spanish": "tenedor" },
                  { "english": "spoon", "german": "Löffel", "spanish": "cuchara" },
                  { "english": "morning", "german": "Morgen", "spanish": "mañana" },
                  { "english": "afternoon", "german": "Nachmittag", "spanish": "tarde" },
                  { "english": "evening", "german": "Abend", "spanish": "noche (temprano)" },
                  { "english": "night", "german": "Nacht", "spanish": "noche" },
                  { "english": "day", "german": "Tag", "spanish": "día" },
                  { "english": "week", "german": "Woche", "spanish": "semana" },
                  { "english": "month", "german": "Monat", "spanish": "mes" },
                  { "english": "year", "german": "Jahr", "spanish": "año" },
                  { "english": "today", "german": "heute", "spanish": "hoy" },
                  { "english": "tomorrow", "german": "morgen", "spanish": "mañana" },
                  { "english": "yesterday", "german": "gestern", "spanish": "ayer" },
                  { "english": "now", "german": "jetzt", "spanish": "ahora" },
                  { "english": "soon", "german": "bald", "spanish": "pronto" },
                  { "english": "always", "german": "immer", "spanish": "siempre" },
                  { "english": "never", "german": "nie", "spanish": "nunca" },
                  { "english": "sometimes", "german": "manchmal", "spanish": "a veces" },
                  { "english": "often", "german": "oft", "spanish": "a menudo" },
                  { "english": "yes", "german": "ja", "spanish": "sí" },
                  { "english": "no", "german": "nein", "spanish": "no" },
                  { "english": "maybe", "german": "vielleicht", "spanish": "quizás" }
                  //TODO: more words

            ]

      },
      {
            id: "Sports",
            title: "Sports",
            description: "Common sports terms, including football vocabulary, from basic to B2 level.",
            cards: [
                  { english: "soccer", german: "Fußball", spanish: "fútbol" },
                  { english: "tennis", german: "Tennis", spanish: "tenis" },
                  { english: "basketball", german: "Basketball", spanish: "baloncesto" },
                  { english: "goalkeeper", german: "Torwart", spanish: "portero" },
                  { english: "center", german: "Mitte", spanish: "centro" },
                  { english: "shot", german: "Schuss", spanish: "tiro" },
                  { english: "pass", german: "Pass", spanish: "pase" },
                  { english: "defender", german: "Verteidiger", spanish: "defensor" },
                  { english: "midfielder", german: "Mittelfeldspieler", spanish: "centrocampista" },
                  { english: "forward", german: "Stürmer", spanish: "delantero" },
                  { english: "referee", german: "Schiedsrichter", spanish: "árbitro" },
                  { english: "penalty", german: "Strafstoß", spanish: "penalti" },
                  { english: "corner", german: "Ecke", spanish: "córner" },
                  { english: "kickoff", german: "Anstoß", spanish: "saque inicial" },
                  { english: "football pitch", german: "Fußballfeld", spanish: "campo de fútbol" },
                  { english: "goalpost", german: "Torpfosten", spanish: "poste de la portería" },
                  { english: "crossbar", german: "Querlatte", spanish: "travesaño" },
                  { english: "offside", german: "Abseits", spanish: "fuera de juego" },
                  { english: "free kick", german: "Freistoß", spanish: "tiro libre" },
                  { english: "header", german: "Kopfball", spanish: "cabezazo" },
                  { english: "dribble", german: "Dribbeln", spanish: "regatear" },
                  { english: "tackle", german: "Zweikampf", spanish: "entrada/tacleada" },
                  { english: "foul", german: "Foul", spanish: "falta" },
                  { english: "yellow card", german: "Gelbe Karte", spanish: "tarjeta amarilla" },
                  { english: "red card", german: "Rote Karte", spanish: "tarjeta roja" },
                  { english: "substitution", german: "Auswechslung", spanish: "cambio/sustitución" },
                  { english: "injury time", german: "Nachspielzeit", spanish: "tiempo añadido" },
                  { english: "half-time", german: "Halbzeit", spanish: "descanso/medio tiempo" },
                  { english: "full-time", german: "Ende der Spielzeit", spanish: "final del partido" },
                  { english: "scoreboard", german: "Anzeigetafel", spanish: "marcador" },
                  { english: "stadium", german: "Stadion", spanish: "estadio" },
                  { english: "audience", german: "Publikum", spanish: "público" },
                  { english: "coach", german: "Trainer", spanish: "entrenador" },
                  { english: "captain", german: "Kapitän", spanish: "capitán" },
                  { english: "formation", german: "Spielaufstellung", spanish: "formación" },
                  { english: "line-up", german: "Aufstellung", spanish: "alineación" },
                  { english: "warm-up", german: "Aufwärmen", spanish: "calentamiento" },
                  { english: "cleats", german: "Fußballschuhe", spanish: "botas de fútbol" },
                  { english: "jersey", german: "Trikot", spanish: "camiseta" },
                  { english: "shin guards", german: "Schienbeinschoner", spanish: "espinilleras" },
                  { english: "whistle", german: "Pfeife", spanish: "silbato" },
                  { english: "huddle", german: "Versammlung", spanish: "grupo/círculo" },
                  { english: "rugby", german: "Rugby", spanish: "rugby" },
                  { english: "volleyball", german: "Volleyball", spanish: "voleibol" },
                  { english: "baseball", german: "Baseball", spanish: "béisbol" },
                  { english: "cricket", german: "Cricket", spanish: "críquet" },
                  { english: "golf", german: "Golf", spanish: "golf" },
                  { english: "swimming", german: "Schwimmen", spanish: "natación" },
                  { english: "running", german: "Laufen", spanish: "correr" },
                  { english: "jogging", german: "Joggen", spanish: "trote" },
                  { english: "marathon", german: "Marathon", spanish: "maratón" },
                  { english: "sprint", german: "Sprint", spanish: "sprint" },
                  { english: "relay race", german: "Staffellauf", spanish: "carrera de relevos" },
                  { english: "hurdles", german: "Hürdenlauf", spanish: "carreras de vallas" },
                  { english: "high jump", german: "Hochsprung", spanish: "salto de altura" },
                  { english: "long jump", german: "Weitsprung", spanish: "salto de longitud" },
                  { english: "pole vault", german: "Stabhochsprung", spanish: "salto con pértiga" },
                  { english: "shot put", german: "Kugelstoßen", spanish: "lanzamiento de peso" },
                  { english: "javelin throw", german: "Speerwurf", spanish: "lanzamiento de jabalina" },
                  { english: "discus throw", german: "Diskuswurf", spanish: "lanzamiento de disco" },
                  { english: "boxing", german: "Boxen", spanish: "boxeo" },
                  { english: "karate", german: "Karate", spanish: "karate" },
                  { english: "judo", german: "Judo", spanish: "judo" },
                  { english: "taekwondo", german: "Taekwondo", spanish: "taekwondo" },
                  { english: "archery", german: "Bogenschießen", spanish: "tiro con arco" },
                  { english: "skiing", german: "Skifahren", spanish: "esquí" },
                  { english: "snowboarding", german: "Snowboarden", spanish: "snowboard" },
                  { english: "surfing", german: "Surfen", spanish: "surf" },
                  { english: "skateboarding", german: "Skateboarden", spanish: "skate" }
            ]
      },
      {
            id: "Adjectives",
            title: "Adjectives",
            description: "List of common adjectives, from basic to B2 level.",
            cards: [
                  { english: "big", german: "groß", spanish: "grande" },
                  { english: "small", german: "klein", spanish: "pequeño" },
                  { english: "fast", german: "schnell", spanish: "rápido" },
                  { english: "slow", german: "langsam", spanish: "lento" },
                  { english: "happy", german: "glücklich", spanish: "feliz" },
                  { english: "sad", german: "traurig", spanish: "triste" },
                  { english: "tall", german: "groß", spanish: "alto" },
                  { english: "short", german: "klein/kurz", spanish: "bajo/corto" },
                  { english: "hot", german: "heiß", spanish: "caliente" },
                  { english: "cold", german: "kalt", spanish: "frío" },
                  { english: "old", german: "alt", spanish: "viejo" },
                  { english: "young", german: "jung", spanish: "joven" },
                  { english: "strong", german: "stark", spanish: "fuerte" },
                  { english: "weak", german: "schwach", spanish: "débil" },
                  { english: "beautiful", german: "schön", spanish: "hermoso/bonito" },
                  { english: "ugly", german: "hässlich", spanish: "feo" },
                  { english: "smart", german: "klug", spanish: "inteligente" },
                  { english: "stupid", german: "dumm", spanish: "tonto" },
                  { english: "kind", german: "nett/freundlich", spanish: "amable" },
                  { english: "rude", german: "unhöflich", spanish: "grosero" },
                  { english: "rich", german: "reich", spanish: "rico" },
                  { english: "poor", german: "arm", spanish: "pobre" },
                  { english: "clean", german: "sauber", spanish: "limpio" },
                  { english: "dirty", german: "schmutzig", spanish: "sucio" },
                  { english: "full", german: "voll", spanish: "lleno" },
                  { english: "empty", german: "leer", spanish: "vacío" },
                  { english: "easy", german: "einfach", spanish: "fácil" },
                  { english: "difficult", german: "schwierig", spanish: "difícil" },
                  { english: "expensive", german: "teuer", spanish: "caro" },
                  { english: "cheap", german: "billig", spanish: "barato" },
                  { english: "new", german: "neu", spanish: "nuevo" },
                  { english: "interesting", german: "interessant", spanish: "interesante" },
                  { english: "boring", german: "langweilig", spanish: "aburrido" },
                  { english: "funny", german: "lustig", spanish: "gracioso" },
                  { english: "serious", german: "ernsthaft", spanish: "serio" },
                  { english: "brave", german: "mutig", spanish: "valiente" },
                  { english: "shy", german: "schüchtern", spanish: "tímido" },
                  { english: "friendly", german: "freundlich", spanish: "amistoso" },
                  { english: "lonely", german: "einsam", spanish: "solo" },
                  { english: "angry", german: "wütend", spanish: "enfadado" },
                  { english: "calm", german: "ruhig", spanish: "tranquilo" },
                  { english: "excited", german: "aufgeregt", spanish: "emocionado" },
                  { english: "nervous", german: "nervös", spanish: "nervioso" },
                  { english: "confident", german: "selbstbewusst", spanish: "seguro de sí mismo" },
                  { english: "curious", german: "neugierig", spanish: "curioso" },
                  { english: "generous", german: "großzügig", spanish: "generoso" },
                  { english: "selfish", german: "egoistisch", spanish: "egoísta" },
                  { english: "polite", german: "höflich", spanish: "cortés" },
                  { english: "impatient", german: "ungeduldig", spanish: "impaciente" },
                  { english: "patient", german: "geduldig", spanish: "paciente" },
                  { english: "ambitious", german: "ehrgeizig", spanish: "ambicioso" },
                  { english: "lazy", german: "faul", spanish: "perezoso" },
                  { english: "hardworking", german: "fleißig", spanish: "trabajador" },
                  { english: "creative", german: "kreativ", spanish: "creativo" },
                  { english: "practical", german: "praktisch", spanish: "práctico" },
                  { english: "sensitive", german: "empfindlich", spanish: "sensible" },
                  { english: "independent", german: "unabhängig", spanish: "independiente" },
                  { english: "dependent", german: "abhängig", spanish: "dependiente" },
                  { english: "optimistic", german: "optimistisch", spanish: "optimista" },
                  { english: "pessimistic", german: "pessimistisch", spanish: "pesimista" },
                  { english: "honest", german: "ehrlich", spanish: "honesto" },
                  { english: "dishonest", german: "unehrlich", spanish: "deshonesto" },
                  { english: "careful", german: "vorsichtig", spanish: "cuidadoso" },
                  { english: "careless", german: "nachlässig", spanish: "descuidado" },
                  { english: "flexible", german: "flexibel", spanish: "flexible" },
                  { english: "stubborn", german: "stur", spanish: "terco" },
                  { english: "sociable", german: "gesellig", spanish: "sociable" },
                  { english: "introverted", german: "introvertiert", spanish: "introvertido" },
                  { english: "extroverted", german: "extrovertiert", spanish: "extrovertido" },
                  { english: "reliable", german: "zuverlässig", spanish: "confiable" },
                  { english: "unreliable", german: "unzuverlässig", spanish: "no confiable" },
                  { english: "talented", german: "talentiert", spanish: "talentoso" },
                  { english: "untalented", german: "unbegabt", spanish: "sin talento" },
                  { english: "energetic", german: "energiegeladen", spanish: "enérgico" },
                  { english: "exhausted", german: "erschöpft", spanish: "agotado" },
                  { english: "curious", german: "neugierig", spanish: "curioso" },
                  { english: "indifferent", german: "gleichgültig", spanish: "indiferente" },
                  { english: "jealous", german: "eifersüchtig", spanish: "celoso" },
                  { english: "grateful", german: "dankbar", spanish: "agradecido" },
                  { english: "guilty", german: "schuldig", spanish: "culpable" },
                  { english: "innocent", german: "unschuldig", spanish: "inocente" },
                  { english: "mature", german: "reif", spanish: "maduro" },
                  { english: "immature", german: " unreif", spanish: "inmaduro" },
                  { english: "modest", german: "bescheiden", spanish: "modesto" },
                  { english: "arrogant", german: "arrogant", spanish: "arrogante" },
                  { english: "suspicious", german: "misstrauisch", spanish: "sospechoso" },
                  { english: "trustworthy", german: "vertrauenswürdig", spanish: "confiable" }
            ]
      },
];